OBJS	= main.o
SOURCE	= main.c
HEADER	= lemmatizer.h nlpc.h preprocess.h stemmer.h summary.h tfidf.h word2vec.h
OUT	    = CAI
CC	    = gcc
FLAGS	= -g -c -Wall
LFLAGS	= 

all: $(OBJS)
	$(CC) -g $(OBJS) -o $(OUT) $(LFLAGS)

main.o: main.c
	$(CC) $(FLAGS) main.c 


clean:
	rm -f $(OBJS) $(OUT)